export const predefinedGames = [
  "7 Wonders",
  "7 Wonders Duel",
  "Agricola",
  "Anachrony",
  "Arkham Horror",
  "Azul",
  "Betrayal at House on the Hill",
  "Blood Rage",
  "Brass: Birmingham",
  "Calico",
  "Carcassonne",
  "Cascadia",
  "Catan",
  "Chess",
  "Clank!",
  "Codenames",
  "Concordia",
  "Cosmic Encounter",
  "Coup",
  "Dead of Winter",
  "Dixit",
  "Dominion",
  "Dungeons and Dragons",
  "Everdell",
  "Gloomhaven",
  "Jaipur",
  "King of Tokyo",
  "Lords of Waterdeep",
  "Lost Ruins of Arnak",
  "Mansions of Madness",
  "Monopoly",
  "Pandemic",
  "Patchwork",
  "Pax Pamir",
  "Power Grid",
  "Root",
  "Rummikub Twist",
  "Santorini",
  "Scythe",
  "Sheriff of Nottingham",
  "Small World",
  "Spirit Island",
  "Splendor",
  "Splendor Duel",
  "Splendor Marvel",
  "Star Realms",
  "Terraforming Mars",
  "The Castles of Burgundy",
  "The Crew",
  "The Quacks of Quedlinburg",
  "The Resistance",
  "Ticket to Ride",
  "Tinderblox",
  "Twilight Struggle",
  "Viticulture",
  "Warhammer 40K",
  "Warhammer Killteam",
  "Wingspan",
  "Werewolf",
  "The Dracula VS Van Helsing",
  "Quest for El Dorado",
  "Dixit Odyssey",
  "Crossing",
  "Cheese Thief",
  "Salem 1692",
  "Avalon",
  "KONG KANG",
  "Insider",
  "OneNight Werewolf ภาคหลัก",
  "OneNight Werewolf ภาคเสริม",
  "Kakerlaken Poker",
];
