export const predefinedGames = [
  "7 Wonders",
  "7 Wonders Duel",
  "Agricola",
  "Anachrony",
  "Arkham Horror",
  "Avalon",
  "Azul",
  "Betrayal at House on the Hill",
  "Blood Rage",
  "Brass: Birmingham",
  "Calico",
  "Carcassonne",
  "Cascadia",
  "Catan",
  "Cheese Thief",
  "Chess",
  "Clank!",
  "Codenames",
  "Concordia",
  "Cosmic Encounter",
  "Coup",
  "Crossing",
  "Dead of Winter",
  "Dixit",
  "Dixit Odyssey",
  "Dominion",
  "Dungeons and Dragons",
  "Everdell",
  "Gloomhaven",
  "Insider",
  "Jaipur",
  "Kakerlaken Poker",
  "King of Tokyo",
  "KONG KANG",
  "Lords of Waterdeep",
  "Lost Ruins of Arnak",
  "Mansions of Madness",
  "Monopoly",
  "OneNight Werewolf ภาคหลัก",
  "OneNight Werewolf ภาคเสริม",
  "Pandemic",
  "Patchwork",
  "Pax Pamir",
  "Power Grid",
  "Quest for El Dorado",
  "Root",
  "Rummikub Twist",
  "Salem 1692",
  "Santorini",
  "Scythe",
  "Sheriff of Nottingham",
  "Small World",
  "Spirit Island",
  "Splendor",
  "Splendor Duel",
  "Splendor Marvel",
  "Star Realms",
  "Terraforming Mars",
  "The Castles of Burgundy",
  "The Crew",
  "The Dracula VS Van Helsing",
  "The Quacks of Quedlinburg",
  "The Resistance",
  "Ticket to Ride",
  "Tinderblox",
  "Twilight Struggle",
  "Viticulture",
  "Warhammer 40K",
  "Warhammer Killteam",
  "Werewolf",
  "Wingspan",
];
